language: cpp
dist: trusty
sudo: required
compiler:
- gcc
- clang
os:
- linux
- osx
env:
  global:
      - CXX_EXTRA="-mssse3"
matrix:
  include:
    - os: linux
      arch: arm64
      compiler: gcc
      env:
       - CXX_EXTRA=""

    - os: linux
      arch: arm64
      compiler: clang
      env:
       - CXX_EXTRA=""
       - CONFIGURE_EXTRA="--disable-native-opt"

script: sh autogen.sh && ./configure CXXFLAGS="-O2 -g $CXX_EXTRA" $CONFIGURE_EXTRA --enable-custom-allocator && make liblocalzlib.a && make -j4 && make check && make clean && ./configure CXXFLAGS="-O2 -g $CXX_EXTRA" $CONFIGURE_EXTRA --disable-advanced-jpeg-features --enable-custom-allocator && make liblocalzlib.a && make -j4 && make check && make clean && CXXFLAGS="-O2 $CXX_EXTRA -DALLOW_3_OR_4_SCALING_FACTOR -DALLOW_FOUR_COLORS" ./configure CXXFLAGS="-O2 $CXX_EXTRA -g" $CONFIGURE_EXTRA && make liblocalzlib.a && make -j4 && make check && make clean && ./configure CXXFLAGS="-O2 $CXX_EXTRA -g" $CONFIGURE_EXTRA --disable-vectorization --enable-custom-allocator  && make liblocalzlib.a && make -j4 && make check && make clean && ./configure CXXFLAGS="-O2 $CXX_EXTRA -g" $CONFIGURE_EXTRA --enable-ans-experimental && make liblocalzlib.a && make -j4 && make check
